# -*- coding: utf-8 -*-
"""readCSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kiIjs-CneqJnUCoTN0ngw5__BaeDxJOO
"""

import re
from collections import namedtuple
from openpyxl import load_workbook
import warnings

# For Colab runtime - must choose file 'CourseCatalogSpring2020.xlsx' from local storage
#from google.colab import files
#uploaded = files.upload()

def create_course_dict():
    """
    Creates a dictionary containing course info.
    Keys: namedtuple of the form ('program, designation')
    Values: namedtuple of the form('name, prereqs, credits')
            prereqs is a tuple of prereqs where each prereq has the same form as the keys
    """
    warnings.simplefilter("ignore")
    wb = load_workbook('CourseCatalogSpring2020.xlsx')
    catalog = wb.get_sheet_by_name('catalog')
    Course = namedtuple('Course', 'program, designation')
    CourseInfo = namedtuple('CourseInfo', 'credits, terms, prereqs')
    course_dict = {}
    for row in range(1, catalog.max_row + 1):
        key = Course(get_val(catalog, 'A', row), get_val(catalog, 'B', row))
        prereqs = tuple(tuple(get_split_course(prereq) for prereq in prereqs.split())
                   for prereqs in none_split(get_val(catalog, 'E', row)))
        val = CourseInfo(get_val(catalog, 'C', row), tuple(get_val(catalog, 'D', row).split()), prereqs)
        course_dict[key] = val
    return course_dict


def get_split_course(course):
    """
    Parses a course from programdesignation into the ('program, designation') form.
    e.g. 'CS1101' -> ('CS', '1101')
    """
    return tuple(split_course for course_part in re.findall('((?:[A-Z]+-)?[A-Z]+)(.+)', course)
                 for split_course in course_part)


def none_split(val):
    """Handles calling split on a None value by returning the empty list."""
    return val.split(', ') if val else ()


def get_val(catalog, col, row):
    """Returns the value of a cell."""
    return catalog[col + str(row)].value


def print_dict(dict, n = -1):
    """Simply prints the first n value's of a dictionary's key and values 
    line by line."""
    n = len(dict) if n == -1 else n
    for index, key in enumerate(dict):
        if index == n: break 
        print(key, dict[key])

#course_dict = create_course_dict()
#print_dict(course_dict, 5)
